name: Use Reusable
on: workflow_dispatch

permissions:
  contents: read

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: "24.x"
      upload-artifact: true
